services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    environment:
      # Browser hits the backend directly via localhost:8080
      API_BASE: "http://localhost:8080"
      PUBLIC_API_KEY: "pub_example_key"
      # WARNING: only set this if the frontend is for your own admin use
      ADMIN_API_KEY: "adm_example_key"
