services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    environment:
      API_BASE: ${API_BASE}
      PUBLIC_API_KEY: ${PUBLIC_API_KEY}
      ADMIN_API_KEY: ${ADMIN_API_KEY}